# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UPQSDK' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SVProgressHUD'
  pod 'Socket.IO-Client-Swift', '~> 14.0'
  pod 'googleapis', :path => '.'

  # Pods for UPQSDK

end
